
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrentvpn
  namespace: flux-system
spec:
  releaseName: qbittorrentvpn
  chart:
    spec:
      chart: qbittorrentvpn
      sourceRef:
        kind: HelmRepository
        name: lavanda
        namespace: flux-system
      version: "2.0.25"
  interval: 1m0s
  targetNamespace: media-catalog
  install:
    createNamespace: true
    timeout: 3m
    remediation:
      retries: -1
  upgrade:
    timeout: 3m
    remediation:
      retries: 1
      strategy: uninstall  
  values:
    image: 
      tag: 4.6.3-1-02
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        # nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.oauth2-proxy.svc.cluster.local:80/oauth2/auth"
        # nginx.ingress.kubernetes.io/auth-signin: "${oauth2_url}/oauth2/start?rd=https://$host$request_uri$is_args$args"
        external-dns.alpha.kubernetes.io/target: ${external_dns_target}
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: ${host}
          paths: 
            - path: /
              pathType: ImplementationSpecific  
      tls:
        - hosts:
            - ${host}
          secretName: qbittorrentvpn-tls 
    paths: 
      data: /mnt/raw-data/plex-data/qbittorrentvpn-data-downloaded
      downloads: /mnt/nvme-data/qbittorrentvpn-downloads
    environmentVariables:
      - name: VPN_ENABLED
        value: "yes" 
      - name: VPN_PROV
        value: airvpn
      - name: VPN_CLIENT
        value: wireguard
      - name: ENABLE_PRIVOXY
        value: "yes"
      - name: LAN_NETWORK 
        value: 10.42.0.0/16
      - name: NAME_SERVERS 
        value: 1.1.1.1,1.0.0.1
      - name: DEBUG 
        value: true 
      - name: WEBUI_PORT 
        value: 8081
      - name: UMASK 
        value: 000
      - name: PUID 
        value: 568
      - name: PGID 
        value: 568  