apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lavanda
resources:
  - mongodb-credentials.yaml
  - filebot-pvc-RWM.yaml
  - filebot-bot-config.yaml
  - telegram-credentials.yaml
  - ingress-filebot-executor.yaml
  - ingress-secret-basic-auth.yaml

