apiVersion: v1
kind: Secret
metadata:
  name: telegram-credentials
  namespace: lavanda
type: Opaque
data:
  token-filebot: NTIxNTk3Njc5NDpBQUY1RF9ZWWYwRXNiM1ZycXM4Tjdia2dzN1BTcTBjYlFhRQ==
  username-filebot: bGF2YW5kYV9maWxlYm90
  token-classify: NjYxMTg3NzcxNzpBQUhFRmRjb3UzWDRzbVFZUnp4aUtoUEVSWllrT3FDVE5iOA==
  username-classify: bGF2YW5kYV9jbGFzc2lmeV9ib3Q=
  authorized-usernames: bHVpc2NhX2psLCBDYXJsVW5kZXJ0LCBWYXRhbHgsIGNoZW1nLCBOZWJsaW5pbw==
  