---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: threadfin
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/truenas/apps/threadfin/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      host_threadfin: threadfin.lavandadelpatio.es
      external_dns_target: ingress-nginx.lavandadelpatio.es    