apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-controller
  namespace: flux-system
spec:
  path: ./clusters/truenas/apps/ingress-nginx/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: ingress-nginx-ingress-nginx-controller
      namespace: ingress-nginx