apiVersion: v1
kind: Service
metadata:
  name: sonarr-en-{{ include "arr.fullname" . }}
  labels:
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/name: sonarr
spec:
  type: {{ .Values.service.sonarr.type }}
  ports:  
    - port: {{ .Values.service.sonarr.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: sonarr-en
    app.kubernetes.io/name: sonarr-en
