apiVersion: v1
kind: Service
metadata:
  name: radarr-{{ include "arr.fullname" . }}
  labels:
    app.kubernetes.io/instance: radarr
    app.kubernetes.io/name: radarr
spec:
  type: {{ .Values.service.radarr.type }}
  ports:
    - port: {{ .Values.service.radarr.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: radarr
    app.kubernetes.io/name: radarr
