/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.6.3/userguide/multi_project_builds.html
 */

rootProject.name = "lavanda-del-patio"
include("apps:demo", "apps:demo2", "apps:filebot-bot")

pluginManagement {
    repositories {
        mavenCentral()
        maven {
            url = uri("https://maven.pkg.github.com/Lavanda-del-Patio/*") //FIXME: CHANGE TO LUISCAJL
            credentials {
                username = "luiscajl"
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}