apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: ">=6.28.0"
  interval: 1h0m0s
  targetNamespace: external-dns
  install:
    createNamespace: true  
  values:
    sources:
      - ingress
    provider: cloudflare
    cloudflare:
      secretName: api-key 
      email: luiscarlos@jimenezlopez.es
      proxied: false
    registry: "noop"  
