spring:
  application:
    name: lavanda-indexers
  profiles:
    active: dev
  data:
    web:
      pageable:
        one-indexed-parameters: true
management:
  endpoint:
    health:
      probes:
        enabled: true