apiVersion: v1
kind: Service
metadata:
  name: {{ include "plex-rclone-wireguard.fullname" . }}
  labels:
    {{- include "plex-rclone-wireguard.labels" . | nindent 4 }}
  annotations: 
    {{- toYaml .Values.service.annotations | nindent 4 }}  
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "plex-rclone-wireguard.selectorLabels" . | nindent 4 }}
