apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "plex-rclone-wireguard.fullname" . }}
  labels:
    {{- include "plex-rclone-wireguard.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "plex-rclone-wireguard.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "plex-rclone-wireguard.fullname" . }} 
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "plex-rclone-wireguard.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 10
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "plex-rclone-wireguard.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:           
        - name: health-script-init
          image: "busybox"
          command:
            - cp
          args:
            - -v
            - /in/health-script.sh
            - /out/health-script.sh
          volumeMounts:
          - name: health-data
            mountPath: /in
          - name: health
            mountPath: /out   
        - name: permission-fix
          image: busybox
          command: ['sh', '-c']
          args: ['chmod -R 655 /out']
          volumeMounts:
          - name: health
            mountPath: /out                                          
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port}}
              protocol: TCP
          volumeMounts:
            {{- if .Values.volumes.config.enabled }}
            - mountPath: /config
              name: plex-rclone-wireguard-config-volume
            {{- end }}                
            {{- if .Values.volumes.data.enabled }}
            - mountPath: /media
              name: data     
              mountPropagation: Bidirectional  
            {{- end }}          
            - mountPath: /health
              name: health                    
          env:
            {{- range .Values.environmentVariables }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}     
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - /health/health-script.sh
                - readiness
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - /health/health-script.sh
                - liveness
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5   
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}  
      volumes: 
      {{- if .Values.volumes.data.enabled }}
        - name: data
          hostPath:
            path: {{ .Values.volumes.data.path }}
            type: Directory
      {{- end }}                
        - name: health-data
          configMap:
            name: plex-rclone-wireguard-health  
            items:
              - key: health-script.sh
                path: health-script.sh
        - name: health
          emptyDir: {}                          
  {{- if .Values.volumes.config.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: plex-rclone-wireguard-config-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.volumes.config.storageClass }}
        resources:
          requests:
            storage: {{ .Values.volumes.config.size }}    
  {{- end }}                