paths:
  data: /mnt/raw-data/plex-data/qbittorrentvpn-data-downloaded
  downloads: /mnt/nvme-data/qbittorrentvpn-downloads
replicaCount: 1
image:
  repository: binhex/arch-qbittorrentvpn
  pullPolicy: Always
  tag: 4.5.2-1-03    
environmentVariables:
  - name: VPN_ENABLED
    value: "yes" 
  - name: VPN_PROV
    value: airvpn
  - name: VPN_CLIENT
    value: wireguard
  - name: ENABLE_PRIVOXY
    value: "yes"
  - name: LAN_NETWORK 
    value: 10.42.0.0/16
  - name: NAME_SERVERS 
    value: 1.1.1.1,1.0.0.1
  - name: DEBUG 
    value: true 
  - name: WEBUI_PORT 
    value: 8081
  - name: UMASK 
    value: 000
  - name: PUID 
    value: 0
  - name: PGID 
    value: 0  
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: 
  privileged: true
  capabilities:
    add: ["NET_ADMIN", "SYS_TIME","SYS_ADMIN"]

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: qbittorrent-test.lavandadelpatio.es
      paths: 
        - path: /
          pathType: ImplementationSpecific

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
