kind: ConfigMap
apiVersion: v1
metadata:
  name: plex-health 
data:
  liveness.sh: |
    #!/bin/bash
    DIR=/media
    numFiles=`ls $DIR | wc -l`
    echo "Numero de ficheros encontrados en la carpeta" $numFiles
    if [[ $numFiles -gt 1 ]]  && [[ "$(curl -sL -w '%{http_code}' http://localhost:32400/identity -o /dev/null)" = "200"  ]];
    #if [[ $numFiles -gt 1 ]];
    then
      echo 0
    else
      echo "Liveness failed!" 1>&2
      exit 1
    fi