replicaCount: 1

config:
  dataPath: /mnt/rclone-cache-writer
  typeOfrclone-cache: gdrive-writer
  command: |-
      [
       "mount",
       "gdrive-writer:","/data",
       "--config=/config/rclone-cache/rclone-cache.conf",
       "--log-level=INFO",
       "--allow-other",
       "--allow-non-empty",
       "--umask","002",
       "--dir-cache-time","100h", 
       "--poll-interval","15s", 
       "--cache-dir=/cache", 
       "--vfs-cache-mode","writes", 
       "--drive-stop-on-upload-limit"
       ]
volumes:
  config:      
    storageClass: hcloud-volumes
    size: 500Gi    
nodeSelector: 
  kubernetes.io/hostname: rke2-master-3
image:
  repository: rclone/rclone
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext:
  {}
  # fsGroup: 2000
securityContext:
  privileged: true
  capabilities:
    add:
      - SYS_ADMIN
resources:
  limits:
    cpu: 2000m
    memory: 4096Mi
  requests:
    cpu: 400m
    memory: 512Mi

tolerations: []
affinity: {}