apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tdarr.fullname" . }}
  labels:
    {{- include "tdarr.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tdarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tdarr.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tdarr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /app/configs
              name: {{ include "tdarr.fullname" . }}-config-volume  
            - mountPath: /app/server
              name: {{ include "tdarr.fullname" . }}-server-volume  
            # - mountPath: /app/logs
            #   name: {{ include "tdarr.fullname" . }}-logs-volume  
            - mountPath: /media
              name: {{ include "tdarr.fullname" . }}-media-volume  
            - mountPath: /transcode_cache
              name: {{ include "tdarr.fullname" . }}-transcode-volume                                                          
          env:
            {{- range .Values.environmentVariables }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}     
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: httpserver
              containerPort: {{ .Values.service.serverPort }}
              protocol: TCP              
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 60
          #   successThreshold: 1
          #   failureThreshold: 5  
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 5
          #   periodSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 5  
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "tdarr.fullname" . }}-config-volume
          persistentVolumeClaim:
            claimName: {{ include "tdarr.fullname" . }}-config-volume        
        - name: {{ include "tdarr.fullname" . }}-server-volume  
          persistentVolumeClaim:
            claimName: {{ include "tdarr.fullname" . }}-server-volume   
        # - name: {{ include "tdarr.fullname" . }}-logs-volume 
        #   hostPath:
        #     path: {{ .Values.paths.logs }}
        #     type: Directory
        - name: {{ include "tdarr.fullname" . }}-media-volume  
          hostPath:
            path: {{ .Values.paths.media }}
            type: Directory
        - name: {{ include "tdarr.fullname" . }}-transcode-volume
          hostPath:
            path: {{ .Values.paths.transcode }}
            type: Directory                                    
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
