apiVersion: v1
kind: Service
metadata:
  name: {{ include "tdarr.fullname" . }}
  labels:
    {{- include "tdarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.serverPort }}
      targetPort: http
      protocol: TCP
      name: httpserver      
  selector:
    {{- include "tdarr.selectorLabels" . | nindent 4 }}
