
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: flux-system
spec:
  releaseName: flaresolverr
  chart:
    spec:
      chart: flaresolverr
      sourceRef:
        kind: HelmRepository
        name: lavanda
        namespace: flux-system
      version: "0.0.4"
  interval: 1m0s
  targetNamespace: media-catalog
  install:
    createNamespace: true
    timeout: 1m
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 1
      strategy: uninstall  
  values:
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: nginx
        external-dns.alpha.kubernetes.io/target: ${external_dns_target}
      hosts:
        - host: ${host}
          paths: 
            - path: /
              pathType: ImplementationSpecific
   