apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrentvpn.fullname" . }}
  labels:
    {{- include "qbittorrentvpn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8118
      targetPort: 8118
      protocol: TCP
      name: privoxy
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: bittorrent-ui
  selector:
    {{- include "qbittorrentvpn.selectorLabels" . | nindent 4 }}
