apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns-controller
  namespace: flux-system
spec:
  path: ./clusters/truenas/apps/external-dns/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  dependsOn:
    - name: external-dns-config
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: external-dns-external-dns
      namespace: external-dns    