spring:
  application:
    name: lavanda-bt4g-downloader
  profiles:
    active: dev
  data:
    web:
      pageable:
        one-indexed-parameters: true
    mongodb:
      auto-index-creation: true
management:
  endpoint:
    health:
      probes:
        enabled: true