apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: arr
  namespace: flux-system
spec:
  releaseName: arr
  chart:
    spec:
      chart: arr
      sourceRef:
        kind: HelmRepository
        name: lavanda
        namespace: flux-system
      version: "1.0.9"
  interval: 1m0s
  targetNamespace: media-catalog
  install:
    createNamespace: true
    timeout: 3m
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
      strategy: uninstall
  values:
    data:
      path: /mnt/raw-data/plex-data
    ingress:
      enabled: true
      className: ""
      annotations:
        kubernetes.io/ingress.class: nginx
        # nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.oauth2-proxy.svc.cluster.local:80/oauth2/auth"
        # nginx.ingress.kubernetes.io/auth-signin: "${oauth2_url}/oauth2/start?rd=https://$host$request_uri$is_args$args"
        external-dns.alpha.kubernetes.io/target: ${external_dns_target}
        cert-manager.io/cluster-issuer: letsencrypt-production
      sonarr:
        host: ${host_sonarr}
        path: /
        pathType: ImplementationSpecific
      sonarrEn:
        host: ${host_sonarr_en}
        path: /
        pathType: ImplementationSpecific
      radarr:
        host: ${host_radarr}
        path: /
        pathType: ImplementationSpecific
      tls:
        - hosts:
            - ${host_sonarr}
          secretName: sonarr-tls
        - hosts:
            - ${host_sonarr_en}
          secretName: sonarr-en-tls
        - hosts:
            - ${host_radarr}
          secretName: radarr-tls
