apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: "v1.10.1"
  interval: 1h0m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    installCRDs: true
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace