apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: telegram-bots
  namespace: flux-system
spec:
  releaseName: telegram-bots
  chart:
    spec:
      chart: telegram-bots
      sourceRef:
        kind: HelmRepository
        name: lavanda
        namespace: flux-system
      version: "0.0.11"
  interval: 1m0s
  targetNamespace: lavanda
  install:
    createNamespace: true
    timeout: 1m
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 1
      strategy: uninstall
  values:
    image:
      tag: 0.0.78 # {"$imagepolicy": "flux-system:lavanda-telegram-bots-policy:tag"}
    spring:
      profile: pro
