apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tautulli-controller
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/truenas/apps/tautulli/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system