name: Apps:FilebotExecutor:Build:Push
on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - 'apps/filebot-executor/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'
      - name: Test dependencies
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Build native image
        id: build_image
        run: ./scripts/build-image.sh apps:filebot-executor

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to docker hub
        run: ./scripts/push-image.sh ${{ steps.build_image.outputs.DOCKER_IMAGE_NAME }}

